backend:
  name: github
  repo: EvilKingSnowy/Distinctive-Craftsman-LLC
  branch: main
  base_url: https://decap-oauth.netlify.app

media_folder: "assets/gallery"
public_folder: "/assets/gallery"

publish_mode: editorial_workflow

collections:
  - name: "featured"
    label: "Homepage Featured Images"
    files:
      - label: "Featured List"
        name: "featured"
        file: "assets/featured.json"
        fields:
          - label: "Images (in order)"
            name: "images"
            widget: "list"
