backend:
  name: github
  repo: EvilKingSnowy/Distinctive-Craftsman-LLC
  branch: main
  base_url: https://decap-oauth.netlify.app  # quick public OAuth proxy

media_folder: "assets/gallery"
public_folder: "/assets/gallery"

publish_mode: editorial_workflow

collections:
  - name: "featured"
    label: "Homepage Featured Images"
    file: "assets/featured.json"
    format: "json"
    fields:
      - label: "Images (in order)"
        name: "images"
        widget: "list"
